// Code generated by a template
using System;
using System.Data.SqlClient;
using Quantumart.QP8.EntityFrameworkCore;

namespace EntityFrameworkCore.Data
{
    public class EFCoreModelConnectionScope
    {

    }
}
