// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Data
{
    public partial class MarketingProduct: IQPArticle
    {
        public MarketingProduct()
        {
		    Products = new HashSet<Product>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Title); }
			set { _Title = value;}
		}
		private String _Alias;
		public virtual String Alias 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Alias); }
			set { _Alias = value;}
		}
        public virtual Int32? ProductType { get; set; }
		private String _Benefit;
		public virtual String Benefit 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Benefit); }
			set { _Benefit = value;}
		}
		private String _ShortBenefit;
		public virtual String ShortBenefit 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_ShortBenefit); }
			set { _ShortBenefit = value;}
		}
		private String _Legal;
		public virtual String Legal 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Legal); }
			set { _Legal = value;}
		}
		private String _Description;
		public virtual String Description 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Description); }
			set { _Description = value;}
		}
		private String _ShortDescription;
		public virtual String ShortDescription 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_ShortDescription); }
			set { _ShortDescription = value;}
		}
		private String _Purpose;
		public virtual String Purpose 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Purpose); }
			set { _Purpose = value;}
		}
        public virtual Int32? Family_ID { get; set; }
		private String _TitleForFamily;
		public virtual String TitleForFamily 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_TitleForFamily); }
			set { _TitleForFamily = value;}
		}
		private String _CommentForFamily;
		public virtual String CommentForFamily 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_CommentForFamily); }
			set { _CommentForFamily = value;}
		}
        public virtual Int32? MarketingSign_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<Product> Products { get; set; }
	}
}
	
