// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EFCore.Models;
namespace EntityFrameworkCore.Data
{
    public partial class ProductParameter: IQPArticle
    {
        public ProductParameter()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return _Title; }
			set { _Title = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Group_ID { get; set; }
        public virtual Int32? BaseParameter_ID { get; set; }
        public virtual Int32? Zone_ID { get; set; }
        public virtual Int32? Direction_ID { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Double? NumValue { get; set; }
		private String _Value;
		public virtual String Value 
		{ 
			get { return _Value; }
			set { _Value = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Unit_ID { get; set; }
		private String _Legal;
		public virtual String Legal 
		{ 
			get { return _Legal; }
			set { _Legal = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _ShortTitle;
		public virtual String ShortTitle 
		{ 
			get { return _ShortTitle; }
			set { _ShortTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _ShortValue;
		public virtual String ShortValue 
		{ 
			get { return _ShortValue; }
			set { _ShortValue = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? MatrixParameter_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual Product Product { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Product_ID { get; set; }
		#region Generated Content properties
        // public Int32 Group_IDExact { get { return this.Group_ID == null ? default(Int32) : this.Group_ID.Value; } }
        // public Int32 BaseParameter_IDExact { get { return this.BaseParameter_ID == null ? default(Int32) : this.BaseParameter_ID.Value; } }
        // public Int32 Zone_IDExact { get { return this.Zone_ID == null ? default(Int32) : this.Zone_ID.Value; } }
        // public Int32 Direction_IDExact { get { return this.Direction_ID == null ? default(Int32) : this.Direction_ID.Value; } }
        // public Int32 SortOrderExact { get { return this.SortOrder == null ? default(Int32) : this.SortOrder.Value; } }
        // public Double NumValueExact { get { return this.NumValue == null ? default(Double) : this.NumValue.Value; } }
        // public Int32 Unit_IDExact { get { return this.Unit_ID == null ? default(Int32) : this.Unit_ID.Value; } }
        // public Int32 MatrixParameter_IDExact { get { return this.MatrixParameter_ID == null ? default(Int32) : this.MatrixParameter_ID.Value; } }
        // public Int32 OldSiteIdExact { get { return this.OldSiteId == null ? default(Int32) : this.OldSiteId.Value; } }
		#endregion
	}
}
	
