// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EFCore.Models;
namespace EntityFrameworkCore.Data
{
    public partial class Region2RegionForDeniedRegions: IQPLink
    {
		public Region RegionItem;		
		public Region RegionLinkedItem;

		public int RegionItem_ID { get; set; }	
		public int RegionLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 72; }
		}

		public int Id { get { return RegionItem_ID; } }
        public int LinkedItemId { get { return RegionLinkedItem_ID; } }
	}

	public partial class Region2RegionForBackwardForDeniedRegions: IQPLink
    {
		public Region RegionItem;		
		public Region RegionLinkedItem;

		public int RegionItem_ID { get; set; }	
		public int RegionLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 72; }
		}

	   public int Id { get { return RegionLinkedItem_ID; } }
       public int LinkedItemId { get { return RegionItem_ID; } }

	}

}
	
	
