namespace Quantumart.QP8.EntityFrameworkCore.Generator.SimpleTemplates
{
    internal static class IQPFormService
    {
        public static string GetTemplate(string ns)
        {
            return @$"
// Code generated by a source generator template
namespace {ns}
{{
    public interface IQPFormService
    {{
        string GetFormNameByNetNames(string netContentName, string netFieldName);
        string ReplacePlaceholders(string text);
    }}
}}";
        }
    }
}