using System.Threading;

namespace Quantumart.QP8.EntityFrameworkCore.Generator.SimpleTemplates
{
    internal static class IQPLink
    {
        public static string GetTemplate(string ns, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return @$"
// Code generated by a source generator template
using System;
using System.Collections;

namespace {ns}
{{
    public interface IQPLink
    {{
        int Id {{ get; set; }}
        int LinkedItemId {{ get; set; }}
        int LinkId {{ get; }}

        IQPArticle Item {{ get; }}
        IQPArticle LinkedItem {{ get; }}
    }}

}}";
        }
    }
}