using System.Threading;

namespace Quantumart.QP8.EntityFrameworkCore.Generator.SimpleTemplates
{
    internal static class ISchemaProvider
    {
        public static string GetTemplate(string ns, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return @$"
// Code generated by a source generator template

using Quantumart.QP8.EntityFrameworkCore.Generator.Models;

namespace {ns}
{{
    public interface ISchemaProvider
    {{
        ModelReader GetSchema();
        object GetCacheKey();
    }}
}}";
        }
    }
}