using System.Threading;

namespace Quantumart.QP8.EntityFrameworkCore.Generator.SimpleTemplates
{
    internal static class StatusType
    {
        public static string GetTemplate(string ns, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return @$"
// Code generated by a source generator template
using System;

namespace {ns}
{{
    public partial class StatusType
    {{
        public Int32 Id {{ get; set; }}
        public string StatusTypeName {{ get; set; }}
        public int Weight {{ get; set; }}
        public Int32 SiteId {{ get; set; }}
    }}
}}";
        }
    }
}