namespace Quantumart.QP8.EntityFrameworkCore.Generator.Templates
{
    internal static class ConnectionScope
    {
        public static string GetTemplate(string ns, GenerationContext context)
        {
            return @$"
// Code generated by a source generator template
using System;
using System.Data.SqlClient;

namespace {ns}
{{
    public class {context.Model.Schema.ClassName}ConnectionScope
    {{}}
}}";
        }
    }
}