// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Tests.Pg
{
    public partial class AfiellFieldsItem: IQPArticle
    {
        public AfiellFieldsItem()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalString;
		public virtual String String 
		{ 
			get { return _internalString; }
			set { _internalString = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Integer { get; set; }
        public virtual Decimal? Decimal { get; set; }
        public virtual Boolean? Boolean { get; set; }
        public virtual DateTime? Date { get; set; }
        public virtual TimeSpan? Time { get; set; }
        public virtual DateTime? DateTime { get; set; }
        public virtual String File { get; set; }
        public virtual String Image { get; set; }
		private String _internalTextBox;
		public virtual String TextBox 
		{ 
			get { return _internalTextBox; }
			set { _internalTextBox = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalVisualEdit;
		public virtual String VisualEdit 
		{ 
			get { return _internalVisualEdit; }
			set { _internalVisualEdit = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual String DynamicImage { get; set; }
		private String _internalEnum;
		public virtual String Enum 
		{ 
			get { return _internalEnum; }
			set { _internalEnum = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
	}
} 	
