// Code generated by a template
using System;
using System.Data.SqlClient;
using Quantumart.QP8.EFCore.Models;

namespace EntityFrameworkCore.Templates
{
    public class EFCoreModelConnectionScope
    {

    }
}
