// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Templates
{
    public partial class MarketingProduct: IQPArticle
    {
        public MarketingProduct()
        {
		    Products = new HashSet<Product>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalTitle;
		public virtual String Title 
		{ 
			get { return _internalTitle; }
			set { _internalTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalAlias;
		public virtual String Alias 
		{ 
			get { return _internalAlias; }
			set { _internalAlias = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? ProductType { get; set; }
		private String _internalBenefit;
		public virtual String Benefit 
		{ 
			get { return _internalBenefit; }
			set { _internalBenefit = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalShortBenefit;
		public virtual String ShortBenefit 
		{ 
			get { return _internalShortBenefit; }
			set { _internalShortBenefit = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalLegal;
		public virtual String Legal 
		{ 
			get { return _internalLegal; }
			set { _internalLegal = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalDescription;
		public virtual String Description 
		{ 
			get { return _internalDescription; }
			set { _internalDescription = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalShortDescription;
		public virtual String ShortDescription 
		{ 
			get { return _internalShortDescription; }
			set { _internalShortDescription = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalPurpose;
		public virtual String Purpose 
		{ 
			get { return _internalPurpose; }
			set { _internalPurpose = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Family_ID { get; set; }
		private String _internalTitleForFamily;
		public virtual String TitleForFamily 
		{ 
			get { return _internalTitleForFamily; }
			set { _internalTitleForFamily = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalCommentForFamily;
		public virtual String CommentForFamily 
		{ 
			get { return _internalCommentForFamily; }
			set { _internalCommentForFamily = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? MarketingSign_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<Product> Products { get; set; }
	}
} 	
