// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Templates
{
    public partial class ProductParameter: IQPArticle
    {
        public ProductParameter()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _internalTitle;
		public virtual String Title 
		{ 
			get { return _internalTitle; }
			set { _internalTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? GroupMapped_ID { get; set; }
        public virtual Int32? BaseParameter_ID { get; set; }
        public virtual Int32? Zone_ID { get; set; }
        public virtual Int32? Direction_ID { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Double? NumValue { get; set; }
		private String _internalValue;
		public virtual String Value 
		{ 
			get { return _internalValue; }
			set { _internalValue = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Unit_ID { get; set; }
		private String _internalLegal;
		public virtual String Legal 
		{ 
			get { return _internalLegal; }
			set { _internalLegal = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalShortTitle;
		public virtual String ShortTitle 
		{ 
			get { return _internalShortTitle; }
			set { _internalShortTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalShortValue;
		public virtual String ShortValue 
		{ 
			get { return _internalShortValue; }
			set { _internalShortValue = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? MatrixParameter_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual Product Product { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Product_ID { get; set; }
	}
} 	
