// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Templates
{
    public partial class ProductParameter: IQPArticle
    {
        public ProductParameter()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Title); }
			set { _Title = value;}
		}
        public virtual Int32? GroupMapped_ID { get; set; }
        public virtual Int32? BaseParameter_ID { get; set; }
        public virtual Int32? Zone_ID { get; set; }
        public virtual Int32? Direction_ID { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Double? NumValue { get; set; }
		private String _Value;
		public virtual String Value 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Value); }
			set { _Value = value;}
		}
        public virtual Int32? Unit_ID { get; set; }
		private String _Legal;
		public virtual String Legal 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Legal); }
			set { _Legal = value;}
		}
		private String _ShortTitle;
		public virtual String ShortTitle 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_ShortTitle); }
			set { _ShortTitle = value;}
		}
		private String _ShortValue;
		public virtual String ShortValue 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_ShortValue); }
			set { _ShortValue = value;}
		}
        public virtual Int32? MatrixParameter_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual Product Product { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Product_ID { get; set; }
	}
}
	
