// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EntityFrameworkCore;
namespace EntityFrameworkCore.Templates
{
    public partial class ProductParameter: IQPArticle
    {
        public ProductParameter()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return _Title; }
			set { _Title = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? GroupMapped_ID { get; set; }
        public virtual Int32? BaseParameter_ID { get; set; }
        public virtual Int32? Zone_ID { get; set; }
        public virtual Int32? Direction_ID { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Double? NumValue { get; set; }
		private String _Value;
		public virtual String Value 
		{ 
			get { return _Value; }
			set { _Value = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Unit_ID { get; set; }
		private String _Legal;
		public virtual String Legal 
		{ 
			get { return _Legal; }
			set { _Legal = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _ShortTitle;
		public virtual String ShortTitle 
		{ 
			get { return _ShortTitle; }
			set { _ShortTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _ShortValue;
		public virtual String ShortValue 
		{ 
			get { return _ShortValue; }
			set { _ShortValue = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? MatrixParameter_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual Product Product { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Product_ID { get; set; }
	}
}
	
