// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Templates
{
    public partial class Product: IQPArticle
    {
        public Product()
        {
		    Parameters = new HashSet<ProductParameter>();
		    MobileTariffs = new HashSet<MobileTariff>();
		    Regions = new HashSet<Product2RegionForRegions>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual Int32? Type { get; set; }
        public virtual String PDF { get; set; }
		private String _internalLegal;
		public virtual String Legal 
		{ 
			get { return _internalLegal; }
			set { _internalLegal = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalBenefit;
		public virtual String Benefit 
		{ 
			get { return _internalBenefit; }
			set { _internalBenefit = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? SortOrder { get; set; }
        public virtual Int32? MarketingSign_ID { get; set; }
        public virtual DateTime? StartDate { get; set; }
        public virtual DateTime? EndDate { get; set; }
		private String _internalArchiveTitle;
		public virtual String ArchiveTitle 
		{ 
			get { return _internalArchiveTitle; }
			set { _internalArchiveTitle = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _internalArchiveNotes;
		public virtual String ArchiveNotes 
		{ 
			get { return _internalArchiveNotes; }
			set { _internalArchiveNotes = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual MarketingProduct MarketingProduct { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? MarketingProduct_ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<ProductParameter> Parameters { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 1192)/Product MobileTariffs
		/// </summary>
		public  ICollection<MobileTariff> MobileTariffs { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<Product2RegionForRegions> Regions { get; set; }
	}
} 	
