// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Templates
{
    public partial class Product2RegionForRegions: IQPLink
    {
		public Product ProductItem { get; set; }		
		public Region RegionLinkedItem { get; set; }

		public int ProductItemId { get; set; }	
		public int RegionLinkedItemId { get; set; }

		public int LinkId
		{
			get { return 21; }
		}

		public int Id 
		{ 
			get { return ProductItemId; } 
			set { ProductItemId = value; } 
		}
        public int LinkedItemId 
		{ 
			get { return RegionLinkedItemId; }
			set { RegionLinkedItemId = value; }
		}
		public IQPArticle Item { get { return ProductItem; } }		
		public IQPArticle LinkedItem { get { return RegionLinkedItem; } }
	}

	public partial class Region2ProductForBackwardForRegions: IQPLink
    {
		public Product ProductLinkedItem { get; set; }		
		public Region RegionItem { get; set; }

		public int ProductLinkedItemId { get; set; }	
		public int RegionItemId { get; set; }

		public int LinkId
		{
			get { return 21; }
		}

                    
		public int Id 
		{ 
			get { return ProductLinkedItemId; }
			set { ProductLinkedItemId = value; }
		}
        public int LinkedItemId 
		{ 
			get { return RegionItemId; } 
			set { RegionItemId = value; }
		}
		public IQPArticle Item { get { return ProductLinkedItem; } }		
		public IQPArticle LinkedItem { get { return RegionItem; } }

	}

}
	
	
