// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace EntityFrameworkCore.Templates
{
    public partial class Region2RegionForAllowedRegions: IQPLink
    {
		public Region RegionItem;		
		public Region RegionLinkedItem;

		public int RegionItem_ID { get; set; }	
		public int RegionLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 71; }
		}

		public int Id { get { return RegionItem_ID; } }
        public int LinkedItemId { get { return RegionLinkedItem_ID; } }
	}

	public partial class Region2RegionForBackwardForAllowedRegions: IQPLink
    {
		public Region RegionItem;		
		public Region RegionLinkedItem;

		public int RegionItem_ID { get; set; }	
		public int RegionLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 71; }
		}

	   public int Id { get { return RegionLinkedItem_ID; } }
       public int LinkedItemId { get { return RegionItem_ID; } }

	}

}
