// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Tests
{
    public partial class AfiellFieldsItem: IQPArticle
    {
        public AfiellFieldsItem()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _String;
		public virtual String String 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_String); }
			set { _String = value;}
		}
        public virtual Int32? Integer { get; set; }
        public virtual Decimal? Decimal { get; set; }
        public virtual Boolean? Boolean { get; set; }
        public virtual DateTime? Date { get; set; }
        public virtual TimeSpan? Time { get; set; }
        public virtual DateTime? DateTime { get; set; }
        public virtual String File { get; set; }
        public virtual String Image { get; set; }
		private String _TextBox;
		public virtual String TextBox 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_TextBox); }
			set { _TextBox = value;}
		}
		private String _VisualEdit;
		public virtual String VisualEdit 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_VisualEdit); }
			set { _VisualEdit = value;}
		}
        public virtual String DynamicImage { get; set; }
		private String _Enum;
		public virtual String Enum 
		{ 
			get { return EFCoreModel.Current.ReplacePlaceholders(_Enum); }
			set { _Enum = value;}
		}
	}
}
	
