// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EFCore.Models;
namespace EntityFrameworkCore.Tests
{
    public partial class AfiellFieldsItem: IQPArticle
    {
        public AfiellFieldsItem()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _String;
		public virtual String String 
		{ 
			get { return _String; }
			set { _String = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual Int32? Integer { get; set; }
        public virtual Decimal? Decimal { get; set; }
        public virtual Boolean? Boolean { get; set; }
        public virtual DateTime? Date { get; set; }
        public virtual TimeSpan? Time { get; set; }
        public virtual DateTime? DateTime { get; set; }
        public virtual String File { get; set; }
        public virtual String Image { get; set; }
		private String _TextBox;
		public virtual String TextBox 
		{ 
			get { return _TextBox; }
			set { _TextBox = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		private String _VisualEdit;
		public virtual String VisualEdit 
		{ 
			get { return _VisualEdit; }
			set { _VisualEdit = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
        public virtual String DynamicImage { get; set; }
		private String _Enum;
		public virtual String Enum 
		{ 
			get { return _Enum; }
			set { _Enum = EFCoreModel.Current.ReplacePlaceholders(value);}
		}
		#region Generated Content properties
        // public string FileUrl { get; set; }
        // public string ImageUrl { get; set; }
        // public string DynamicImageUrl { get; set; }
        // public string FileUploadPath { get; set; }
        // public string ImageUploadPath { get; set; }
        // public Int32 IntegerExact { get { return this.Integer == null ? default(Int32) : this.Integer.Value; } }
        // public Decimal DecimalExact { get { return this.Decimal == null ? default(Decimal) : this.Decimal.Value; } }
        // public Boolean BooleanExact { get { return this.Boolean == null ? default(Boolean) : this.Boolean.Value; } }
		#endregion
	}
}
	
