// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EntityFrameworkCore;
namespace EntityFrameworkCore.Tests
{
    public partial class MtMItemForUpdate2MtMDictionaryForUpdateForReference: IQPLink
    {
		public MtMItemForUpdate MtMItemForUpdateItem { get; set; }		
		public MtMDictionaryForUpdate MtMDictionaryForUpdateLinkedItem { get; set; }

		public int MtMItemForUpdateItem_ID { get; set; }	
		public int MtMDictionaryForUpdateLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 149; }
		}

		public int Id { get { return MtMItemForUpdateItem_ID; } }
        public int LinkedItemId { get { return MtMDictionaryForUpdateLinkedItem_ID; } }
	}

	public partial class MtMItemForUpdate2MtMDictionaryForUpdateForBackwardForReference: IQPLink
    {
		public MtMItemForUpdate MtMDictionaryForUpdateItem { get; set; }		
		public MtMDictionaryForUpdate MtMItemForUpdateLinkedItem { get; set; }

		public int MtMDictionaryForUpdateItem_ID { get; set; }	
		public int MtMItemForUpdateLinkedItem_ID { get; set; }

		public int LinkId
		{
			get { return 149; }
		}

                    
		public int Id { get { return MtMDictionaryForUpdateItem_ID; } }
        public int LinkedItemId { get { return MtMItemForUpdateLinkedItem_ID; } }

	}

}
	
	
	
	
	
	
	
	
	
	
	
