// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Tests
{
    public partial class MtMItemForUpdate2MtMDictionaryForUpdateForReference: IQPLink
    {
		public MtMItemForUpdate MtMItemForUpdateItem { get; set; }		
		public MtMDictionaryForUpdate MtMDictionaryForUpdateLinkedItem { get; set; }

		public int MtMItemForUpdateItemId { get; set; }	
		public int MtMDictionaryForUpdateLinkedItemId { get; set; }

		public int LinkId
		{
			get { return 149; }
		}

		public int Id 
		{ 
			get { return MtMItemForUpdateItemId; } 
			set { MtMItemForUpdateItemId = value; } 
		}
        public int LinkedItemId 
		{ 
			get { return MtMDictionaryForUpdateLinkedItemId; }
			set { MtMDictionaryForUpdateLinkedItemId = value; }
		}
		public IQPArticle Item { get { return MtMItemForUpdateItem; } }		
		public IQPArticle LinkedItem { get { return MtMDictionaryForUpdateLinkedItem; } }
	}

	public partial class MtMDictionaryForUpdate2MtMItemForUpdateForBackwardForReference: IQPLink
    {
		public MtMItemForUpdate MtMItemForUpdateLinkedItem { get; set; }		
		public MtMDictionaryForUpdate MtMDictionaryForUpdateItem { get; set; }

		public int MtMItemForUpdateLinkedItemId { get; set; }	
		public int MtMDictionaryForUpdateItemId { get; set; }

		public int LinkId
		{
			get { return 149; }
		}

                    
		public int Id 
		{ 
			get { return MtMItemForUpdateLinkedItemId; }
			set { MtMItemForUpdateLinkedItemId = value; }
		}
        public int LinkedItemId 
		{ 
			get { return MtMDictionaryForUpdateItemId; } 
			set { MtMDictionaryForUpdateItemId = value; }
		}
		public IQPArticle Item { get { return MtMItemForUpdateLinkedItem; } }		
		public IQPArticle LinkedItem { get { return MtMDictionaryForUpdateItem; } }

	}

}
	
	
	
	
	
	
	
	
	
	
	
