// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EFCore.Models;
namespace EntityFrameworkCore.Tests
{
    public partial class OtMItemToContentWithoutMapping: IQPArticle
    {
        public OtMItemToContentWithoutMapping()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual Int32? OtMReferenceMapping_ID { get; set; }
		#region Generated Content properties
        // public Int32 OtMReferenceMapping_IDExact { get { return this.OtMReferenceMapping_ID == null ? default(Int32) : this.OtMReferenceMapping_ID.Value; } }
		#endregion
	}
}
