// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace EntityFrameworkCore.Tests
{
    public partial class ToSymmetricRelationAtricle2SymmetricRelationArticleForToSymmetricRelation: IQPLink
    {
		public ToSymmetricRelationAtricle ToSymmetricRelationAtricleItem { get; set; }		
		public SymmetricRelationArticle SymmetricRelationArticleLinkedItem { get; set; }

		public int ToSymmetricRelationAtricleItemId { get; set; }	
		public int SymmetricRelationArticleLinkedItemId { get; set; }

		public int LinkId
		{
			get { return 101; }
		}

		public int Id 
		{ 
			get { return ToSymmetricRelationAtricleItemId; } 
			set { ToSymmetricRelationAtricleItemId = value; } 
		}
        public int LinkedItemId 
		{ 
			get { return SymmetricRelationArticleLinkedItemId; }
			set { SymmetricRelationArticleLinkedItemId = value; }
		}
		public IQPArticle Item { get { return ToSymmetricRelationAtricleItem; } }		
		public IQPArticle LinkedItem { get { return SymmetricRelationArticleLinkedItem; } }
	}

	public partial class SymmetricRelationArticle2ToSymmetricRelationAtricleForSymmetricRelation: IQPLink
    {
		public ToSymmetricRelationAtricle ToSymmetricRelationAtricleLinkedItem { get; set; }		
		public SymmetricRelationArticle SymmetricRelationArticleItem { get; set; }

		public int ToSymmetricRelationAtricleLinkedItemId { get; set; }	
		public int SymmetricRelationArticleItemId { get; set; }

		public int LinkId
		{
			get { return 101; }
		}

                    
		public int Id 
		{ 
			get { return ToSymmetricRelationAtricleLinkedItemId; }
			set { ToSymmetricRelationAtricleLinkedItemId = value; }
		}
        public int LinkedItemId 
		{ 
			get { return SymmetricRelationArticleItemId; } 
			set { SymmetricRelationArticleItemId = value; }
		}
		public IQPArticle Item { get { return ToSymmetricRelationAtricleLinkedItem; } }		
		public IQPArticle LinkedItem { get { return SymmetricRelationArticleItem; } }

	}

}
	
